#!/usr/bin/env python3
"""
Verify docs/llms.txt, docs/robots.txt, and docs/sitemap.xml are up to date.

All three files are generated by scripts/generate_llms_txt.py:
  - llms.txt    from data/kev-layer-classifications.json + dashboard DATA blob
  - robots.txt  static + Sitemap: pointer
  - sitemap.xml from the SITEMAP_PAGES list in the script

They should never be hand-edited. If they drift, run:

    python3 scripts/generate_llms_txt.py

This test invokes the generator's own --check mode, which returns a
non-zero exit code if regenerating would change any of the three files.
The sitemap.xml comparison ignores the <lastmod> lines so this test
isn't tripped by the daily date change.

When to add tests here:
  * If you add new sections to llms.txt that depend on additional
    DATA fields, narrow this test to assert specific content (e.g.
    "must contain the string for the new metric").

If this test fails:
  * Run scripts/generate_llms_txt.py and commit the result.
  * If it still fails after regenerating, the underlying data changed
    AND the prose template needs updating — fix both.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent


def main() -> int:
    script = REPO / "scripts" / "generate_llms_txt.py"
    result = subprocess.run(
        [sys.executable, str(script), "--check"],
        capture_output=True,
        text=True,
        cwd=REPO,
    )

    print(result.stdout, end="")
    if result.stderr:
        print(result.stderr, end="", file=sys.stderr)

    if result.returncode != 0:
        print()
        print("[llms-txt] FAILED — docs/llms.txt, docs/robots.txt, or "
              "docs/sitemap.xml is stale.")
        print("  Fix:   python3 scripts/generate_llms_txt.py")
        return 1

    print("[llms-txt] OK — llms.txt + robots.txt + sitemap.xml are up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
