#!/usr/bin/env python3
"""
Pin the FOSS sub-7 server-side exploited dataset + model-scoring headline
numbers so the data guy can audit and so drift is caught loud.

The dataset is generated by the foss_sub7 pipeline (4 stages) documented
at data/FOSS-SUB7-METHODOLOGY.md. The scoring is generated by
scripts/foss_sub7_score.py from data/foss-sub7-unique.json.

This test:
  1. Verifies the canonical record counts (135 distinct CVEs, 156 per-pkg).
  2. Verifies all 4 KEV-confirmed CVEs are present (the strongest evidence
     bucket — losing one means the upstream pull lost or moved an entry).
  3. Re-runs scripts/foss_sub7_score.py and verifies the headline aggregate
     stats match what's pinned in data/foss-sub7-scoring.json (i.e. the
     scorer is deterministic and the on-disk file is current).
  4. Verifies the headline percentages didn't drift outside ±0.5% of the
     2026-04-29 baseline.

If this test fails:
  * If counts changed: the upstream OSV / KEV / MSF / EDB data shifted.
    Re-run the pipeline (data/FOSS-SUB7-METHODOLOGY.md) and bump the
    pinned numbers below if the new values are correct.
  * If the scorer disagrees with the on-disk JSON: re-run
    scripts/foss_sub7_score.py and commit.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DATASET = REPO / "data" / "foss-sub7-exploited.json"
UNIQUE = REPO / "data" / "foss-sub7-unique.json"
SCORING = REPO / "data" / "foss-sub7-scoring.json"
SCORE_SCRIPT = REPO / "scripts" / "foss_sub7_score.py"

# Pinned baselines (2026-04-29).
EXPECTED_DISTINCT_CVES = 135
EXPECTED_PER_PKG_RECORDS = 156
EXPECTED_KEV_CVES = {
    "CVE-2020-11652",   # Salt arbitrary directory access
    "CVE-2023-44487",   # HTTP/2 rapid reset (across multiple HTTP servers)
    "CVE-2025-31125",   # Vite server.fs.deny bypass
    "CVE-2025-35939",   # Craft CMS chained session storage
}

# Headline aggregate baselines. Tolerance ±0.5pp absolute.
EXPECTED_HEADLINES = {
    "np_di_raw_pct": 82.2,
    "np_di_dq_pct": 85.9,
    "hacker_sa_pct": 25.9,
    "union_pct": 87.4,
}
TOLERANCE_PP = 0.5


def main() -> int:
    fails = 0

    # 1. Per-pkg dataset shape
    rows = json.load(DATASET.open())
    distinct = sorted({r["cve"] for r in rows})
    if len(rows) != EXPECTED_PER_PKG_RECORDS:
        print(f"FAIL: per-package row count drifted: {len(rows)} != {EXPECTED_PER_PKG_RECORDS}")
        fails += 1
    else:
        print(f"OK  : per-package row count = {len(rows)}")

    if len(distinct) != EXPECTED_DISTINCT_CVES:
        print(f"FAIL: distinct CVE count drifted: {len(distinct)} != {EXPECTED_DISTINCT_CVES}")
        fails += 1
    else:
        print(f"OK  : distinct CVE count = {len(distinct)}")

    # 2. KEV cohort intact
    kev_in_dataset = {
        r["cve"] for r in rows
        if "KEV" in (r.get("evidence_sources") or [])
    }
    missing_kev = EXPECTED_KEV_CVES - kev_in_dataset
    extra_kev = kev_in_dataset - EXPECTED_KEV_CVES
    if missing_kev or extra_kev:
        print(f"FAIL: KEV cohort drifted. missing={sorted(missing_kev)} extra={sorted(extra_kev)}")
        fails += 1
    else:
        print(f"OK  : KEV cohort = {sorted(EXPECTED_KEV_CVES)}")

    # 3. Unique-CVE input file shape (input to scorer)
    unique_rows = json.load(UNIQUE.open())
    if len(unique_rows) != EXPECTED_DISTINCT_CVES:
        print(f"FAIL: foss-sub7-unique.json row count drifted: {len(unique_rows)} != {EXPECTED_DISTINCT_CVES}")
        fails += 1
    else:
        print(f"OK  : foss-sub7-unique.json row count = {len(unique_rows)}")

    # 4. Scorer determinism — re-run it and diff the aggregate
    on_disk = json.load(SCORING.open())
    on_disk_agg = on_disk["metadata"]["aggregate"]

    # Cache the on-disk file, regenerate, diff, restore if needed.
    cached = SCORING.read_bytes()
    try:
        result = subprocess.run(
            [sys.executable, str(SCORE_SCRIPT)],
            capture_output=True, text=True, cwd=REPO,
        )
        if result.returncode != 0:
            print(f"FAIL: scorer crashed:\n{result.stderr[-500:]}")
            fails += 1
        else:
            regen = json.load(SCORING.open())
            regen_agg = regen["metadata"]["aggregate"]
            differing_keys = [
                k for k in on_disk_agg
                if k in regen_agg and on_disk_agg[k] != regen_agg[k]
                and not isinstance(on_disk_agg[k], dict)
            ]
            if differing_keys:
                print(f"FAIL: scorer output drifted from on-disk file. Keys: {differing_keys}")
                for k in differing_keys:
                    print(f"      {k}: on-disk={on_disk_agg[k]} regen={regen_agg[k]}")
                fails += 1
            else:
                print(f"OK  : scorer reproduces data/foss-sub7-scoring.json exactly")
    finally:
        # Restore in case the regen produced bit-identical-but-formatting-different
        SCORING.write_bytes(cached)

    # 5. Headline percentages within tolerance
    for key, expected in EXPECTED_HEADLINES.items():
        actual_str = on_disk_agg.get(key, "")
        actual = float(str(actual_str).rstrip("%"))
        delta = abs(actual - expected)
        if delta > TOLERANCE_PP:
            print(f"FAIL: {key} drifted: {actual}% (baseline {expected}%, tolerance ±{TOLERANCE_PP}pp)")
            fails += 1
        else:
            print(f"OK  : {key} = {actual}% (baseline {expected}%, Δ={delta:.2f}pp)")

    if fails:
        print(f"\n{fails} check(s) failed.")
        return 1
    print("\nAll FOSS sub-7 scoring checks passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
