#!/usr/bin/env python3
"""
Verify docs/llms.txt and docs/robots.txt are up to date with the live data.

Both files are generated by scripts/generate_llms_txt.py from
data/kev-layer-classifications.json + the dashboard DATA blob. They
should never be hand-edited. If they drift from what the generator
would produce, run:

    python3 scripts/generate_llms_txt.py

This test invokes the generator's own --check mode, which returns a
non-zero exit code if regenerating would change either file.

When to add tests here:
  * If you add new sections to llms.txt that depend on additional
    DATA fields, narrow this test to assert specific content (e.g.
    "must contain the string for the new metric").

If this test fails:
  * Run scripts/generate_llms_txt.py and commit the result.
  * If it still fails after regenerating, the underlying data changed
    AND the prose template needs updating — fix both.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent


def main() -> int:
    script = REPO / "scripts" / "generate_llms_txt.py"
    result = subprocess.run(
        [sys.executable, str(script), "--check"],
        capture_output=True,
        text=True,
        cwd=REPO,
    )

    print(result.stdout, end="")
    if result.stderr:
        print(result.stderr, end="", file=sys.stderr)

    if result.returncode != 0:
        print()
        print("[llms-txt] FAILED — docs/llms.txt or docs/robots.txt is stale.")
        print("  Fix:   python3 scripts/generate_llms_txt.py")
        return 1

    print("[llms-txt] OK — generated files are up to date with DATA")
    return 0


if __name__ == "__main__":
    sys.exit(main())
