#!/usr/bin/env python3
"""
Verify data/seven-year-npdi-events.json is up to date with the live inputs.

The dataset is generated by scripts/build_seven_year_npdi.py from:
  - cached-data/osv/osv_cwe_results.json (24 popular network-parsing libs)
  - data/_osv-alias-cache.json (CVE alias resolution; cached, never re-fetched)
  - data/kev-snapshot-2026-04-23.json (KEV outcome flag)
  - cached-data/epss/{metasploit,exploitdb,epss}_results.json
  - analysis-scripts/spring_manifest_analysis.py (manifest membership)

The dataset should never be hand-edited. If it drifts from what the
generator would produce, run:

    python3 scripts/build_seven_year_npdi.py

This test invokes the generator's --check mode (exit 1 if regenerating
would change the on-disk file) and additionally enforces a few sanity
invariants on the generated structure.

If this test fails:
  * Run scripts/build_seven_year_npdi.py and commit the result.
  * If it still fails, an upstream input changed (cache, manifest, KEV
    snapshot) and the analysis needs review.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DATASET = REPO / "data" / "seven-year-npdi-events.json"


def main() -> int:
    fails = 0

    # 1. Regeneration freshness check
    script = REPO / "scripts" / "build_seven_year_npdi.py"
    result = subprocess.run(
        [sys.executable, str(script), "--check"],
        capture_output=True, text=True, cwd=REPO,
    )
    print(result.stdout, end="")
    if result.stderr:
        print(result.stderr, end="", file=sys.stderr)
    if result.returncode != 0:
        fails += 1
        print(f"FAIL — regeneration would change {DATASET.name}")

    # 2. Structural invariants on the dataset
    if not DATASET.exists():
        fails += 1
        print(f"FAIL — {DATASET.name} does not exist")
    else:
        ds = json.load(open(DATASET))
        events = ds.get("events", [])
        summary = ds.get("summary", {})

        # Each event has the expected fields
        for k in ("description", "methodology", "input_sources", "summary", "events"):
            if k not in ds:
                fails += 1
                print(f"FAIL — top-level key missing: {k}")

        required_fields = ("osv_id", "cve", "package", "ecosystem", "cwe",
                           "is_np", "is_di", "in_kev", "in_metasploit",
                           "in_exploitdb", "in_manifest", "summary")
        for e in events[:3]:
            missing = [f for f in required_fields if f not in e]
            if missing:
                fails += 1
                print(f"FAIL — event {e.get('osv_id', '?')} missing fields: {missing}")

        # Every event is is_np=True is_di=True (filter contract)
        bad = [e for e in events if not (e.get("is_np") and e.get("is_di"))]
        if bad:
            fails += 1
            print(f"FAIL — {len(bad)} events are not NP+DI but appear in dataset")

        # Summary counts match recomputed
        if summary.get("total_events") != len(events):
            fails += 1
            print(f"FAIL — summary.total_events={summary.get('total_events')} != "
                  f"len(events)={len(events)}")
        in_kev_recomputed = sum(1 for e in events if e["in_kev"])
        if summary.get("in_kev_count") != in_kev_recomputed:
            fails += 1
            print(f"FAIL — summary.in_kev_count={summary.get('in_kev_count')} != "
                  f"recomputed {in_kev_recomputed}")
        in_manifest_recomputed = sum(1 for e in events if e["in_manifest"])
        if summary.get("in_manifest_count") != in_manifest_recomputed:
            fails += 1
            print(f"FAIL — summary.in_manifest_count={summary.get('in_manifest_count')} "
                  f"!= recomputed {in_manifest_recomputed}")

        # Sanity floors — if these fail, something upstream broke badly
        if len(events) < 50:
            fails += 1
            print(f"FAIL — fewer than 50 NP+DI events ({len(events)}); "
                  f"OSV cache may be incomplete")
        if in_kev_recomputed < 3:
            fails += 1
            print(f"FAIL — fewer than 3 in-KEV NP+DI events ({in_kev_recomputed}); "
                  f"alias cache or KEV snapshot may be stale")

    if fails:
        print(f"\n[seven-year-npdi] {fails} FAILED")
        return 1
    print(f"[seven-year-npdi] OK — dataset is reproducible and structurally sound")
    return 0


if __name__ == "__main__":
    sys.exit(main())
